input_values = [
    ("KF", "sr"),
    ("OO", "vy"),
    ("start", "FP"),
    ("FP", "end"),
    ("vy", "mi"),
    ("vy", "KF"),
    ("vy", "na"),
    ("start", "sr"),
    ("FP", "lh"),
    ("sr", "FP"),
    ("na", "FP"),
    ("end", "KF"),
    ("na", "mi"),
    ("lh", "KF"),
    ("end", "lh"),
    ("na", "start"),
    ("wp", "KF"),
    ("mi", "KF"),
    ("vy", "sr"),
    ("vy", "lh"),
    ("sr", "mi"),
]
test_values = [
    ("start", "A"),
    ("start", "b"),
    ("A", "c"),
    ("A", "b"),
    ("b", "d"),
    ("A", "end"),
    ("b", "end"),
]
